spring.application.name=lead-management
server.port=8080

app.base-url=${APP_BASE_URL}
app.frontend-url=${FRONTEND_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

lms.jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

lms.base-url=${LMS_BASE_URL}

# Cashfree
cashfree.client-id=${CASHFREE_CLIENT_ID}
cashfree.client-secret=${CASHFREE_CLIENT_SECRET}
cashfree.environment=SANDBOX
cashfree.webhook-secret=${CASHFREE_WEBHOOK_SECRET}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true